var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=f.print||console.log.bind(console),m=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var ma=f.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,v,x,ra,y,ka=a=>a.startsWith("file://");
function sa(){var a=na.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a);f.HEAP64=ra=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var z=0,A=null;function ta(a){f.onAbort?.(a);a="Aborted("+a+")";m(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;
async function va(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ua&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}
async function xa(a){var b=ua;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return wa(b,a)}var ya={60688:()=>{f._webapi_input=a=>{B(()=>f._webapi_input_internal(C(a)))};f._webapi_load_file=a=>{B(()=>f._webapi_load_file_internal(C(a)))}}};
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(f)},Ba=[],Ca=[],Da=()=>{var a=f.preRun.shift();Ca.unshift(a)},Ea=f.noExitRuntime||!0,Fa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Fa)return Fa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ga=0,E={},Ha=a=>{a instanceof za||"unwind"==a||ha(1,a)},Ia=a=>{oa=a;Ea||0<Ga||(f.onExit?.(a),q=!0);ha(a,new za(a))},Ja=a=>{oa=a;Ia(a)},Ka=()=>{if(!(Ea||0<Ga))try{var a=oa;oa=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!q)try{a(),Ka()}catch(b){Ha(b)}},Ma=[],Va=(a,b)=>{Na=a;Oa=b;if(Pa)if(Qa||=!0,0==a)F=function(){setTimeout(Ra,Math.max(0,Sa+b-performance.now())|0)};else if(1==a)F=function(){Ta(Ra)};else if(2==
a){if("undefined"==typeof Ua)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ua=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ua=setImmediate;F=function(){Ua(Ra)}}},db=(a,b,c,d,e)=>{function h(){return g<Wa?(Ka(),!1):!0}Pa=a;Xa=d;var g=Wa;Qa=!1;Ra=function(){if(!q)if(0<
Ya.length){var l=Ya.shift();l.le(l.ae);if(Za){var n=Za,p=0==n%1?n-1:Math.floor(n);Za=l.ce?p:(8*n+(p+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Za??0,p=$a.he??0,n?n<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(Ra,0)}else if(h())if(ab=ab+1|0,1==Na&&1<Oa&&0!=ab%Oa)F();else{0==Na&&(Sa=performance.now());a:if(!q){for(l of bb)if(!1===l())break a;La(a);for(n of cb)n()}h()&&F()}};e||(0<b?Va(0,1E3/b):Va(1,1),F());if(c)throw"unwind";
},Qa=!1,F=null,Wa=0,Pa=null,Xa=0,Na=0,Oa=0,ab=0,Ya=[],bb=[],cb=[];function eb(){F=null;Wa++}var fb=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===fb)fb=b+1E3/60;else for(;b+2>=fb;)fb+=1E3/60;setTimeout(a,Math.max(fb-b,0))}}var $a={},Sa,Ra,Ua,Za;function gb(a){var b=H.bd[a];b.target.removeEventListener(b.ad,b.Id,b.cd);H.bd.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:H.td&&H.Wd.rd){var a=H.kd;H.kd=[];for(var b of a)b.wd(...b.Dd)}}function I(a){if(!a.target)return-4;if(a.dd)a.Id=function(c){++H.td;H.Wd=a;hb();a.ed(c);hb();--H.td},a.target.addEventListener(a.ad,a.Id,a.cd),H.bd.push(a);else for(var b=0;b<H.bd.length;++b)H.bd[b].target==a.target&&H.bd[b].ad==a.ad&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={be:0,me:0,ud:0,qd:0,Ad:0,yd:0,sd:0,fe:0,re:0,ee:0,ke:0,vd:0,ze:0,xd:0,oe(a,b,c){r.set(r.subarray(b,b+c),a)},te(){for(;H.bd.length;)gb(H.bd.length-1);H.kd=[]},td:0,kd:[],de(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of H.kd)if(e.wd==a&&d(e.Dd,c))return;H.kd.push({wd:a,Md:b,Dd:c});H.kd.sort((h,g)=>h.Md<g.Md)},ve(a){H.kd=H.kd.filter(b=>b.wd!=a)},bd:[],ue:(a,b)=>{for(var c=0;c<H.bd.length;++c)H.bd[c].target!=a||b&&b!=H.bd[c].ad||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},jb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?D(t,a):"":a;return jb[a]||("undefined"!=typeof document?document.querySelector(a):null)},kb=a=>0>jb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},lb=[],mb,K=a=>{var b=lb[a];b||(a>=lb.length&&(lb.length=a+1),lb[a]=b=mb.get(a));return b},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=
0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},nb=(a,b,c,d,e,h)=>{H.sd||(H.sd=M(256));a={target:J(a),ad:h,dd:d,ed:(g=event)=>{var l=g.target.id?g.target.id:"",n=H.sd;L(ib(g.target),n+0,
128);L(l,n+128,128);K(d)(e,n,b)&&g.preventDefault()},cd:c};return I(a)},ob=(a,b,c,d,e,h)=>{H.ud||(H.ud=M(160));a={target:J(a),ad:h,dd:d,ed:g=>{var l=H.ud;y[l>>3]=g.timeStamp;var n=l>>2;u[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;L(g.key||"",l+32,32);L(g.code||"",l+64,32);L(g.char||"",l+96,32);L(g.locale||"",l+128,32);K(d)(e,l,b)&&g.preventDefault()},cd:c};return I(a)},pb=(a,b,c)=>{y[a>>
3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=kb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},qb=(a,b,c,d,e,h)=>{H.qd||(H.qd=M(64));a=J(a);return I({target:a,rd:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ad:h,dd:d,ed:(g=event)=>{pb(H.qd,g,a);K(d)(e,H.qd,b)&&g.preventDefault()},
cd:c})},rb=(a,b,c,d,e)=>{H.vd||(H.vd=M(257));return I({target:a,ad:e,dd:d,ed:(h=event)=>{var g=H.vd,l=document.pointerLockElement||document.ld||document.Ed||document.Cd;r[g]=!!l;var n=l?.id||"";L(ib(l),g+1,128);L(n,g+129,128);K(d)(20,g,b)&&h.preventDefault()},cd:c})},sb=(a,b,c,d,e)=>I({target:a,ad:e,dd:d,ed:(h=event)=>{K(d)(38,0,b)&&h.preventDefault()},cd:c}),tb=(a,b,c,d)=>{H.yd||(H.yd=M(36));a=J(a);return I({target:a,ad:"resize",dd:d,ed:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=
H.yd;u[g>>2]=0;u[g+4>>2]=h.clientWidth;u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;K(d)(10,g,b)&&e.preventDefault()}}},cd:c})},ub=(a,b,c,d,e,h)=>{H.xd||(H.xd=M(1552));a=J(a);return I({target:a,rd:"touchstart"==h||"touchend"==h,ad:h,dd:d,ed:g=>{var l={},n=g.touches;for(var p of n)p.Jd=p.Ld=0,l[p.identifier]=p;for(var w of g.changedTouches)w.Jd=1,l[w.identifier]=w;for(var R of g.targetTouches)l[R.identifier].Ld=
1;n=H.xd;y[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;p=n+16;w=kb(a);R=0;for(let G of Object.values(l))if(l=p>>2,u[l]=G.identifier,u[l+1]=G.screenX,u[l+2]=G.screenY,u[l+3]=G.clientX,u[l+4]=G.clientY,u[l+5]=G.pageX,u[l+6]=G.pageY,r[p+28]=G.Jd,r[p+29]=G.Ld,u[l+8]=G.clientX-(w.left|0),u[l+9]=G.clientY-(w.top|0),p+=48,31<++R)break;u[n+8>>2]=R;K(d)(e,n,b)&&g.preventDefault()},cd:c})},N,vb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},wb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},xb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},yb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},zb=1,Ab=[],O=[],Bb=[],Cb=[],P=[],Q=[],Db=[],Eb=[],S=[],Fb={},Gb=4,Hb=0,Ib=a=>{for(var b=zb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),g=h&&Ib(d);h?(h.name=g,d[g]=h):T||=1282;u[b+4*e>>2]=g}},Kb=(a,b)=>{a.ld||(a.ld=a.getContext,a.getContext=function(d,e){e=a.ld(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Kd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Jb(c,b):0},Jb=(a,b)=>{var c=Ib(Eb),d={handle:c,attributes:b,version:b.Kd,Bd:a};a.canvas&&(a.canvas.$d=d);Eb[c]=d;("undefined"==typeof b.Hd||b.Hd)&&Lb(d);return c},Lb=a=>{a||=V;if(!a.Zd){a.Zd=!0;var b=a.Bd;b.qe=b.getExtension("WEBGL_multi_draw");b.je=b.getExtension("EXT_polygon_offset_clamp");b.ie=b.getExtension("EXT_clip_control");b.Ae=b.getExtension("WEBGL_polygon_mode");vb(b);wb(b);xb(b);b.ge=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ne=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Gd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Gd)b.Gd=b.getExtension("EXT_disjoint_timer_query");yb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Mb=(a,b,c,d,e,h)=>{a={target:J(a),ad:h,dd:d,ed:(g=event)=>{K(d)(e,0,b)&&g.preventDefault()},cd:c};I(a)},Nb=(a,b,c,d)=>{H.Ad||(H.Ad=M(96));return I({target:a,rd:!0,ad:"wheel",dd:d,ed:(e=event)=>{var h=H.Ad;pb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
u[h+88>>2]=e.deltaMode;K(d)(9,h,b)&&e.preventDefault()},cd:c})},Ob=["default","low-power","high-performance"],Pb={},Rb=()=>{if(!Qb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Pb)void 0===Pb[b]?delete a[b]:a[b]=Pb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qb=c}return Qb},Qb,Sb=[null,[],[]],Tb=[],Ub=()=>{var a=yb(N);
return a=a.concat(a.map(b=>"GL_"+b))},Vb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Ub().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Wb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Xb=a=>{var b=Wb(a)+1,c=M(b);c&&L(a,c,b);return c},Yb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Zb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},$b=(a,b,c,d,e)=>{a=Zb(a);b=d*((Hb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Gb-1&-Gb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=N.Xd;if(b){var c=b.md[a];"number"==typeof c&&(b.md[a]=c=N.getUniformLocation(b,b.Ud[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],ac=[],C=a=>{var b=Wb(a)+1,c=bc(b);L(a,c,b);return c},B=a=>{var b=cc();a();dc(b)};f.requestAnimationFrame=Ta;f.pauseMainLoop=eb;f.resumeMainLoop=function(){Wa++;var a=Na,b=Oa,c=Pa;Pa=null;db(c,0,!1,Xa,!0);Va(a,b);F()};f.preMainLoop&&bb.push(f.preMainLoop);f.postMainLoop&&cb.push(f.postMainLoop);for(var Y=0;32>Y;++Y)Tb.push(Array(Y));
var ec=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=ec.subarray(0,Y);var fc=new Int32Array(288);for(Y=0;288>=Y;++Y)ac[Y]=fc.subarray(0,Y);
var tc={ja:function(){return 0},nb:function(){return 0},pb:function(){},sb:()=>ta(""),hb:()=>{Ea=!1;Ga=0},ib:(a,b)=>{E[a]&&(clearTimeout(E[a].id),delete E[a]);if(!b)return 0;var c=setTimeout(()=>{delete E[a];La(()=>gc(a,performance.now()))},b);E[a]={id:c,ye:b};return 0},db:function(a){if(void 0===window.localStorage)return 0;a=a?D(t,a):"";return(a=window.localStorage.getItem(a))?Xb(a):0},hc:function(a,b){void 0!==window.localStorage&&(a=a?D(t,a):"",b=b?D(t,b):"",window.localStorage.setItem(a,b))},
Za:(a,b,c)=>{Ma.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Ma.push(112==d?v[c>>2]:106==d?ra[c>>3]:105==d?u[c>>2]:y[c>>3]);c+=e?8:4}return ya[a](...Ma)},Ra:()=>{eb();Pa=null},ca:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ea:(a,b,c)=>{a=J(a);if(!a)return-4;a=kb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},v:()=>performance.now(),Sa:()=>performance.now(),Xa:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=
t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);sa();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},M:(a,b,c,d)=>nb(a,b,c,d,12,"blur"),ba:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:(a,b,c,d)=>nb(a,b,c,d,13,"focus"),W:(a,b,c,d)=>ob(a,b,c,d,2,"keydown"),U:(a,b,c,d)=>ob(a,b,c,d,1,"keypress"),V:(a,
b,c,d)=>ob(a,b,c,d,3,"keyup"),Ya:(a,b,c)=>{a=K(a);db(a,b,c)},aa:(a,b,c,d)=>qb(a,b,c,d,5,"mousedown"),Z:(a,b,c,d)=>qb(a,b,c,d,33,"mouseenter"),Y:(a,b,c,d)=>qb(a,b,c,d,34,"mouseleave"),_:(a,b,c,d)=>qb(a,b,c,d,8,"mousemove"),$:(a,b,c,d)=>qb(a,b,c,d,6,"mouseup"),P:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ld||document.body.Ed||document.body.Cd))return-1;a=J(a);if(!a)return-4;rb(a,b,c,d,"mozpointerlockchange");rb(a,b,c,d,"webkitpointerlockchange");rb(a,
b,c,d,"mspointerlockchange");return rb(a,b,c,d,"pointerlockchange")},O:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.ld||document.body.Ed||document.body.Cd))return-1;a=J(a);if(!a)return-4;sb(a,b,c,d,"mozpointerlockerror");sb(a,b,c,d,"webkitpointerlockerror");sb(a,b,c,d,"mspointerlockerror");return sb(a,b,c,d,"pointerlockerror")},da:(a,b,c,d)=>tb(a,b,c,d),Q:(a,b,c,d)=>ub(a,b,c,d,25,"touchcancel"),R:(a,b,c,d)=>ub(a,b,c,d,23,"touchend"),S:(a,b,c,d)=>ub(a,b,c,d,24,"touchmove"),
T:(a,b,c,d)=>ub(a,b,c,d,22,"touchstart"),L:(a,b,c,d)=>{Mb(a,b,c,d,31,"webglcontextlost");return 0},K:(a,b,c,d)=>{Mb(a,b,c,d,32,"webglcontextrestored");return 0},X:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Nb(a,b,c,d):-1:-4,Wa:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Ob[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Kd:u[c+4],pe:u[c+5],Hd:r[b+24],Yd:r[b+25],se:u[c+7],we:r[b+
32]};a=J(a);return!a||b.Yd?0:Kb(a,b)},Va:a=>{V=Eb[a];f.ctx=N=V?.Bd;return!a||N?0:-5},qb:(a,b)=>{var c=0;Rb().forEach((d,e)=>{var h=b+c;e=v[a+4*e>>2]=h;for(h=0;h<d.length;++h)r[e++]=d.charCodeAt(h);r[e]=0;c+=d.length+1});return 0},rb:(a,b)=>{var c=Rb();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},ia:()=>52,mb:()=>52,kb:function(){return 70},lb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=t[g+n],w=Sb[a];0===p||10===p?((1===
a?la:m)(D(w)),w.length=0):w.push(p)}e+=l}v[d>>2]=e;return 0},p:a=>N.activeTexture(a),ua:(a,b)=>{N.attachShader(O[a],Q[b])},b:(a,b)=>{35051==a?N.Fd=b:35052==a&&(N.jd=b);N.bindBuffer(a,Ab[b])},a:(a,b,c)=>{N.bindBufferBase(a,b,Ab[c])},l:(a,b)=>{N.bindFramebuffer(a,Bb[b])},Ca:(a,b)=>{N.bindRenderbuffer(a,Cb[b])},o:(a,b)=>{N.bindSampler(a,S[b])},d:(a,b)=>{N.bindTexture(a,P[b])},J:a=>{N.bindVertexArray(Db[a])},F:(a,b,c,d)=>N.blendColor(a,b,c,d),G:(a,b)=>N.blendEquationSeparate(a,b),H:(a,b,c,d)=>N.blendFuncSeparate(a,
b,c,d),wb:(a,b,c,d,e,h,g,l,n,p)=>N.blitFramebuffer(a,b,c,d,e,h,g,l,n,p),Ea:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+b):b,d)},z:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},oa:a=>N.checkFramebufferStatus(a),Qb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),ma:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Pb:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},q:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Vb:a=>{N.compileShader(Q[a])},
fc:(a,b,c,d,e,h,g,l)=>{2<=V.version?N.jd||!g?N.compressedTexImage2D(a,b,c,d,e,h,g,l):N.compressedTexImage2D(a,b,c,d,e,h,t,l,g):N.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,l+g))},dc:(a,b,c,d,e,h,g,l,n)=>{N.jd?N.compressedTexImage3D(a,b,c,d,e,h,g,l,n):N.compressedTexImage3D(a,b,c,d,e,h,g,t,n,l)},ac:()=>{var a=Ib(O),b=N.createProgram();b.name=a;b.pd=b.nd=b.od=0;b.zd=1;O[a]=b;return a},Xb:a=>{var b=Ib(Q);Q[b]=N.createShader(a);return b},C:a=>N.cullFace(a),Ia:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+
4*c>>2],e=Ab[d];e&&(N.deleteBuffer(e),e.name=0,Ab[d]=null,d==N.Fd&&(N.Fd=0),d==N.jd&&(N.jd=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Bb[d];e&&(N.deleteFramebuffer(e),e.name=0,Bb[d]=null)}},m:a=>{if(a){var b=O[a];b?(N.deleteProgram(b),b.name=0,O[a]=null):T||=1281}},A:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Cb[d];e&&(N.deleteRenderbuffer(e),e.name=0,Cb[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},y:a=>{if(a){var b=
Q[a];b?(N.deleteShader(b),Q[a]=null):T||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=P[d];e&&(N.deleteTexture(e),e.name=0,P[d]=null)}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];N.deleteVertexArray(Db[d]);Db[d]=null}},u:a=>N.depthFunc(a),t:a=>{N.depthMask(!!a)},e:a=>N.disable(a),I:a=>{N.disableVertexAttribArray(a)},yb:(a,b,c)=>{N.drawArrays(a,b,c)},Ab:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},na:(a,b)=>{for(var c=Tb[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];N.drawBuffers(c)},Bb:(a,b,
c,d)=>{N.drawElements(a,b,c,d)},Cb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},j:a=>N.enable(a),Mb:a=>{N.enableVertexAttribArray(a)},pa:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,Cb[d])},n:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,P[d],e)},x:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,P[c],d,e)},D:a=>N.frontFace(a),Fa:(a,b)=>{U(a,b,"createBuffer",Ab)},qa:(a,b)=>{U(a,b,"createFramebuffer",Bb)},Da:(a,b)=>{U(a,b,"createRenderbuffer",Cb)},bc:(a,b)=>{U(a,b,"createSampler",S)},Aa:(a,b)=>{U(a,b,
"createTexture",P)},Qa:(a,b)=>{U(a,b,"createVertexArray",Db)},Sb:(a,b)=>N.getAttribLocation(O[a],b?D(t,b):""),c:(a,b)=>Vb(a,b),Zb:(a,b,c,d)=>{a=N.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},ta:(a,b,c)=>{if(c)if(a>=zb)T||=1281;else if(a=O[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.pd){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pd=Math.max(a.pd,N.getActiveUniform(a,b).name.length+
1)}u[c>>2]=a.pd}else if(35722==b){if(!a.nd)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.nd=Math.max(a.nd,N.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.nd}else if(35381==b){if(!a.od)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.od=Math.max(a.od,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.od}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},Ub:(a,b,c,d)=>{a=N.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},ra:(a,b,c)=>{c?35716==b?
(a=N.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(Q[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=N.getShaderParameter(Q[a],b):T||=1281},Na:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Fb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Ub().map(Xb),c=Fb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},sa:(a,b)=>{b=b?D(t,b):"";if(a=O[a]){var c=a,d=c.md,e=c.Vd,h;if(!d){c.md=d={};c.Ud={};var g=N.getProgramParameter(c,
35718);for(h=0;h<g;++h){var l=N.getActiveUniform(c,h);var n=l.name;l=l.size;var p=Yb(n);p=0<p?n.slice(0,p):n;var w=c.zd;c.zd+=l;e[p]=[l,w];for(n=0;n<l;++n)d[w]=n,c.Ud[w++]=p}}c=a.md;d=0;e=b;h=Yb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Vd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},vb:(a,b,c)=>{for(var d=Tb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];N.invalidateFramebuffer(a,d)},$b:a=>{a=O[a];N.linkProgram(a);a.md=0;a.Vd={}},Oa:(a,b)=>{3317==
a?Gb=b:3314==a&&(Hb=b);N.pixelStorei(a,b)},E:(a,b)=>N.polygonOffset(a,b),xb:a=>N.readBuffer(a),Ba:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),va:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},h:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},r:(a,b,c,d)=>N.scissor(a,b,c,d),Wb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*h>>2])?D(t,g,d?v[d+4*h>>2]:void 0):"";e+=g}N.shaderSource(Q[a],e)},Ma:(a,b,c)=>N.stencilFunc(a,b,c),la:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),s:a=>N.stencilMask(a),La:(a,
b,c)=>N.stencilOp(a,b,c),ka:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),ec:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(N.jd){N.texImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var p=Zb(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);N.texImage2D(a,b,c,d,e,h,g,l,p,n);return}}p=n?$b(l,g,d,e,n):null;N.texImage2D(a,b,c,d,e,h,g,l,p)},cc:(a,b,c,d,e,h,g,l,n,p)=>{if(N.jd)N.texImage3D(a,b,c,d,e,h,g,l,n,p);else if(p){var w=Zb(n);N.texImage3D(a,b,c,d,e,h,g,l,n,w,p>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else N.texImage3D(a,b,
c,d,e,h,g,l,n,null)},za:(a,b,c)=>N.texParameteri(a,b,c),ya:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),xa:(a,b,c,d,e,h)=>N.texStorage3D(a,b,c,d,e,h),ub:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(N.jd){N.texSubImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var p=Zb(l);N.texSubImage2D(a,b,c,d,e,h,g,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}n=n?$b(l,g,e,h,n):null;N.texSubImage2D(a,b,c,d,e,h,g,l,n)},tb:(a,b,c,d,e,h,g,l,n,p,w)=>{if(N.jd)N.texSubImage3D(a,b,c,d,e,h,g,l,n,p,w);else if(w){var R=Zb(p);N.texSubImage3D(a,
b,c,d,e,h,g,l,n,p,R,w>>>31-Math.clz32(R.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,g,l,n,p,null)},Lb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Yb:(a,b)=>{N.uniform1i(W(a),b)},Hb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=ac[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Kb:(a,b,c)=>
{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=ac[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=
0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=ac[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=
e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=ac[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Db:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=
d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=O[a];N.useProgram(a);N.Xd=a},Nb:(a,b)=>{N.vertexAttribDivisor(a,b)},Ob:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},k:(a,b,c,d)=>N.viewport(a,b,c,d),gb:Ia,Ua:function(){f.Nd=a=>{0!=
hc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Nd)},Pa:function(){f.Td=a=>{const b=a.clipboardData.getData("text");B(()=>{const c=C(b);ic(c)})};window.addEventListener("paste",f.Td)},Ga:function(){f.xe=[];f.Od=b=>{b.stopPropagation();b.preventDefault()};f.Pd=b=>{b.stopPropagation();b.preventDefault()};f.Qd=b=>{b.stopPropagation();b.preventDefault()};f.Rd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Sd=c;jc(c.length);for(let e=0;e<
c.length;e++)B(()=>{const h=C(c[e].name);kc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);lc(b.clientX,b.clientY,d)};const a=f.gd;a.addEventListener("dragenter",f.Od,!1);a.addEventListener("dragleave",f.Pd,!1);a.addEventListener("dragover",f.Qd,!1);a.addEventListener("drop",f.Rd,!1)},ob:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},gc:function(a){const b=f.Sd;return 0>a||a>=b.length?0:b[a].size},_b:function(a,
b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?mc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),mc(a,1,0,b,g.byteLength,c,d,e))};h.onerror=()=>{mc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Sd[a])},Rb:function(a,b){0!==b&&(document.title=b?D(t,b):"");a=a?D(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?jb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.gd=J(a);f.gd||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);f.gd.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ta:function(){window.removeEventListener("beforeunload",f.Nd)},Ka:function(){window.removeEventListener("paste",f.Td)},Tb:function(){const a=f.gd;a.removeEventListener("dragenter",f.Od);a.removeEventListener("dragleave",f.Pd);a.removeEventListener("dragover",f.Qd);a.removeEventListener("drop",f.Rd)},w:function(){f.gd&&f.gd.requestPointerLock&&f.gd.requestPointerLock()},zb:function(a,b){if(f.gd){if(0===
b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.gd.style.cursor=a}},fb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,
c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ja:function(a){a=a?D(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();
document.execCommand("copy");document.body.removeChild(b)},$a:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];B(()=>{const e=C(c),h=C(d);nc(e,h)})}},bb:function(){return f.hd?f.hd.bufferSize:0},eb:function(a,b,c){f.$c=null;f.hd=null;"undefined"!==typeof AudioContext?f.$c=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.$c=null,console.log("sokol_audio.h: no WebAudio support"));return f.$c?
(console.log("sokol_audio.h: sample rate ",f.$c.sampleRate),f.hd=f.$c.createScriptProcessor(c,0,b),f.hd.onaudioprocess=d=>{const e=d.outputBuffer.length,h=oc(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=x[(h>>2)+(g*p+l)]}}},f.hd.connect(f.$c.destination),a=()=>{f.$c&&"suspended"===f.$c.state&&f.$c.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",
a,{once:!0}),1):0},cb:function(){return f.$c?f.$c.sampleRate:0},ha:function(){const a=f.$c;null!==a&&(f.hd&&f.hd.disconnect(),a.close(),f.$c=null,f.hd=null)},ab:function(){if(f.$c)return"suspended"===f.$c.state?1:0},ga:function(a,b,c,d,e,h){b=b?D(t,b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const n=
new Uint8Array(g.response),p=n.length;p<=h?(t.set(n,e),pc(a,d,p)):qc(a)}else rc(a,g.status)};g.send()},_a:function(a,b){b=b?D(t,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");sc(a,d)}else rc(a,c.status)};c.send()},wa:function(){return navigator.userAgent.includes("Macintosh")?1:0},fa:function(a,b){b=b?D(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);
break;case 2:console.warn(b);break;default:console.info(b)}}},Z;(async function(){function a(c){Z=c.exports;na=Z.ic;sa();mb=Z.Wc;z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:tc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ua??=f.locateFile?f.locateFile("numbersid.wasm",k):k+"numbersid.wasm";return a((await xa(b)).instance)})();var M=a=>(M=Z.kc)(a);
f._fs_emsc_alloc=a=>(f._fs_emsc_alloc=Z.lc)(a);f._fs_emsc_load_snapshot_callback=(a,b,c)=>(f._fs_emsc_load_snapshot_callback=Z.mc)(a,b,c);f._webapi_dbg_connect=()=>(f._webapi_dbg_connect=Z.nc)();f._webapi_dbg_disconnect=()=>(f._webapi_dbg_disconnect=Z.oc)();f._webapi_alloc=a=>(f._webapi_alloc=Z.pc)(a);f._webapi_free=a=>(f._webapi_free=Z.qc)(a);f._webapi_boot=()=>(f._webapi_boot=Z.rc)();f._webapi_reset=()=>(f._webapi_reset=Z.sc)();f._webapi_ready=()=>(f._webapi_ready=Z.tc)();
f._webapi_load=(a,b)=>(f._webapi_load=Z.uc)(a,b);f._webapi_load_file_internal=a=>(f._webapi_load_file_internal=Z.vc)(a);f._webapi_unload_file=()=>(f._webapi_unload_file=Z.wc)();f._webapi_load_snapshot=a=>(f._webapi_load_snapshot=Z.xc)(a);f._webapi_save_snapshot=a=>(f._webapi_save_snapshot=Z.yc)(a);f._webapi_dbg_add_breakpoint=a=>(f._webapi_dbg_add_breakpoint=Z.zc)(a);f._webapi_dbg_remove_breakpoint=a=>(f._webapi_dbg_remove_breakpoint=Z.Ac)(a);f._webapi_dbg_break=()=>(f._webapi_dbg_break=Z.Bc)();
f._webapi_dbg_continue=()=>(f._webapi_dbg_continue=Z.Cc)();f._webapi_dbg_step_next=()=>(f._webapi_dbg_step_next=Z.Dc)();f._webapi_dbg_step_into=()=>(f._webapi_dbg_step_into=Z.Ec)();f._webapi_dbg_cpu_state=()=>(f._webapi_dbg_cpu_state=Z.Fc)();f._webapi_dbg_request_disassembly=(a,b,c)=>(f._webapi_dbg_request_disassembly=Z.Gc)(a,b,c);f._webapi_dbg_read_memory=(a,b)=>(f._webapi_dbg_read_memory=Z.Hc)(a,b);f._webapi_input_internal=a=>(f._webapi_input_internal=Z.Ic)(a);
var ic=f.__sapp_emsc_onpaste=a=>(ic=f.__sapp_emsc_onpaste=Z.Jc)(a),hc=f.__sapp_html5_get_ask_leave_site=()=>(hc=f.__sapp_html5_get_ask_leave_site=Z.Kc)(),jc=f.__sapp_emsc_begin_drop=a=>(jc=f.__sapp_emsc_begin_drop=Z.Lc)(a),kc=f.__sapp_emsc_drop=(a,b)=>(kc=f.__sapp_emsc_drop=Z.Mc)(a,b),lc=f.__sapp_emsc_end_drop=(a,b,c)=>(lc=f.__sapp_emsc_end_drop=Z.Nc)(a,b,c),mc=f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(mc=f.__sapp_emsc_invoke_fetch_cb=Z.Oc)(a,b,c,d,e,h,g,l),uc=f._main=(a,b)=>(uc=f._main=Z.Pc)(a,
b),oc=f.__saudio_emsc_pull=a=>(oc=f.__saudio_emsc_pull=Z.Qc)(a),nc=f.__sargs_add_kvp=(a,b)=>(nc=f.__sargs_add_kvp=Z.Rc)(a,b),sc=f.__sfetch_emsc_head_response=(a,b)=>(sc=f.__sfetch_emsc_head_response=Z.Sc)(a,b),pc=f.__sfetch_emsc_get_response=(a,b,c)=>(pc=f.__sfetch_emsc_get_response=Z.Tc)(a,b,c),rc=f.__sfetch_emsc_failed_http_status=(a,b)=>(rc=f.__sfetch_emsc_failed_http_status=Z.Uc)(a,b),qc=f.__sfetch_emsc_failed_buffer_too_small=a=>(qc=f.__sfetch_emsc_failed_buffer_too_small=Z.Vc)(a),gc=(a,b)=>
(gc=Z.Xc)(a,b),dc=a=>(dc=Z.Yc)(a),bc=a=>(bc=Z.Zc)(a),cc=()=>(cc=Z._c)();function vc(a=[]){var b=uc;a.unshift(fa);var c=a.length,d=bc(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=C(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Ja(h)}catch(g){Ha(g)}}
function wc(a=ea){function b(){f.calledRun=!0;if(!q){Z.jc();f.onRuntimeInitialized?.();f.noInitialRun||vc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();Ba.unshift(c)}Aa(Ba)}}if(0<z)A=wc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();Aa(Ca);0<z?A=wc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();wc();
