var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var ma=g.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,v,x,y,ka=a=>a.startsWith("file://");
function ra(){var a=na.buffer;g.HEAP8=r=new Int8Array(a);g.HEAP16=pa=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAP32=u=new Int32Array(a);g.HEAPU32=v=new Uint32Array(a);g.HEAPF32=x=new Float32Array(a);g.HEAPF64=y=new Float64Array(a);g.HEAP64=new BigInt64Array(a);g.HEAPU64=new BigUint64Array(a)}var z=0,A=null;function sa(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ta&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(g)},za=[],Aa=[],Ba=()=>{var a=g.preRun.shift();Aa.unshift(a)},Ca=g.noExitRuntime||!0,Da="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Da)return Da.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ea=0,C={},Fa=a=>{a instanceof xa||"unwind"==a||ha(1,a)},Ga=a=>{oa=a;Ca||0<Ea||(g.onExit?.(a),q=!0);ha(a,new xa(a))},Ha=a=>{oa=a;Ga(a)},Ia=()=>{if(!(Ca||0<Ea))try{var a=oa;oa=a;Ga(a)}catch(b){Fa(b)}},Ja=a=>{if(!q)try{a(),Ia()}catch(b){Fa(b)}},Qa=(a,b)=>{Ka=a;La=b;if(D)if(Ma||=!0,0==a)E=function(){setTimeout(F,Math.max(0,Na+b-performance.now())|0)};else if(1==a)E=function(){Oa(F)};else if(2==a){if("undefined"==
typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;E=function(){Pa(F)}}},Za=(a,b,c,d,e)=>{function h(){return f<Ra?(Ia(),!1):!0}D=a;Sa=d;var f=Ra;Ma=!1;F=function(){if(!q)if(0<Ta.length){var l=
Ta.shift();l.Nd(l.Cd);if(Ua){var n=Ua,p=0==n%1?n-1:Math.floor(n);Ua=l.Ed?p:(8*n+(p+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ua??0,p=Va.Jd??0,n?n<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(F,0)}else if(h())if(Wa=Wa+1|0,1==Ka&&1<La&&0!=Wa%La)E();else{0==Ka&&(Na=performance.now());a:if(!q){for(l of Xa)if(!1===l())break a;Ja(a);for(n of Ya)n()}h()&&E()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),E());if(c)throw"unwind";},Ma=!1,E=
null,Ra=0,D=null,Sa=0,Ka=0,La=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){E=null;Ra++}var ab=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}var Va={},Na,F,Pa,Ua;function bb(a){var b=H.Ec[a];b.target.removeEventListener(b.Dc,b.kd,b.Fc);H.Ec.splice(a,1)}
function cb(){if(navigator.userActivation?navigator.userActivation.isActive:H.Uc&&H.xd.Sc){var a=H.Lc;H.Lc=[];for(var b of a)b.Xc(...b.ed)}}function I(a){if(!a.target)return-4;if(a.Gc)a.kd=function(c){++H.Uc;H.xd=a;cb();a.Hc(c);cb();--H.Uc},a.target.addEventListener(a.Dc,a.kd,a.Fc),H.Ec.push(a);else for(var b=0;b<H.Ec.length;++b)H.Ec[b].target==a.target&&H.Ec[b].Dc==a.Dc&&bb(b--);return 0}function db(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var H={Dd:0,Od:0,Vc:0,Rc:0,ad:0,Zc:0,Tc:0,Hd:0,Td:0,Gd:0,Md:0,Wc:0,be:0,Yc:0,Qd(a,b,c){r.set(r.subarray(b,b+c),a)},Vd(){for(;H.Ec.length;)bb(H.Ec.length-1);H.Lc=[]},Uc:0,Lc:[],Fd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of H.Lc)if(e.Xc==a&&d(e.ed,c))return;H.Lc.push({Xc:a,od:b,ed:c});H.Lc.sort((h,f)=>h.od<f.od)},Xd(a){H.Lc=H.Lc.filter(b=>b.Xc!=a)},Ec:[],Wd:(a,b)=>{for(var c=0;c<H.Ec.length;++c)H.Ec[c].target!=a||b&&b!=H.Ec[c].Dc||
bb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},eb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?B(t,a):"":a;return eb[a]||("undefined"!=typeof document?document.querySelector(a):null)},fb=a=>0>eb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},gb=[],hb,K=a=>{var b=gb[a];b||(a>=gb.length&&(gb.length=a+1),gb[a]=b=hb.get(a));return b},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=
0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=a.charCodeAt(++h);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},ib=(a,b,c,d,e,h)=>{H.Tc||(H.Tc=M(256));a={target:J(a),Dc:h,Gc:d,Hc:(f=event)=>{var l=f.target.id?f.target.id:"",n=H.Tc;L(db(f.target),n+0,
128);L(l,n+128,128);K(d)(e,n,b)&&f.preventDefault()},Fc:c};return I(a)},jb=(a,b,c,d,e,h)=>{H.Vc||(H.Vc=M(160));a={target:J(a),Dc:h,Gc:d,Hc:f=>{var l=H.Vc;y[l>>3]=f.timeStamp;var n=l>>2;u[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[n+5]=f.charCode;u[n+6]=f.keyCode;u[n+7]=f.which;L(f.key||"",l+32,32);L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);K(d)(e,l,b)&&f.preventDefault()},Fc:c};return I(a)},kb=(a,b,c)=>{y[a>>
3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=fb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,h)=>{H.Rc||(H.Rc=M(64));a=J(a);return I({target:a,Sc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Dc:h,Gc:d,Hc:(f=event)=>{kb(H.Rc,f,a);K(d)(e,H.Rc,b)&&f.preventDefault()},
Fc:c})},mb=(a,b,c,d,e)=>{H.Wc||(H.Wc=M(257));return I({target:a,Dc:e,Gc:d,Hc:(h=event)=>{var f=H.Wc,l=document.pointerLockElement||document.Mc||document.cd||document.bd;r[f]=!!l;var n=l?.id||"";L(db(l),f+1,128);L(n,f+129,128);K(d)(20,f,b)&&h.preventDefault()},Fc:c})},nb=(a,b,c,d,e)=>I({target:a,Dc:e,Gc:d,Hc:(h=event)=>{K(d)(38,0,b)&&h.preventDefault()},Fc:c}),ob=(a,b,c,d)=>{H.Zc||(H.Zc=M(36));a=J(a);return I({target:a,Dc:"resize",Gc:d,Hc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=
H.Zc;u[f>>2]=0;u[f+4>>2]=h.clientWidth;u[f+8>>2]=h.clientHeight;u[f+12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;K(d)(10,f,b)&&e.preventDefault()}}},Fc:c})},pb=(a,b,c,d,e,h)=>{H.Yc||(H.Yc=M(1552));a=J(a);return I({target:a,Sc:"touchstart"==h||"touchend"==h,Dc:h,Gc:d,Hc:f=>{var l={},n=f.touches;for(var p of n)p.ld=p.nd=0,l[p.identifier]=p;for(var w of f.changedTouches)w.ld=1,l[w.identifier]=w;for(var Q of f.targetTouches)l[Q.identifier].nd=
1;n=H.Yc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;p=n+16;w=fb(a);Q=0;for(let G of Object.values(l))if(l=p>>2,u[l]=G.identifier,u[l+1]=G.screenX,u[l+2]=G.screenY,u[l+3]=G.clientX,u[l+4]=G.clientY,u[l+5]=G.pageX,u[l+6]=G.pageY,r[p+28]=G.ld,r[p+29]=G.nd,u[l+8]=G.clientX-(w.left|0),u[l+9]=G.clientY-(w.top|0),p+=48,31<++Q)break;u[n+8>>2]=Q;K(d)(e,n,b)&&f.preventDefault()},Fc:c})},N,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ub=1,vb=[],O=[],wb=[],xb=[],P=[],R=[],yb=[],zb=[],S=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),f=h&&Db(d);h?(h.name=f,d[f]=h):T||=1282;u[b+4*e>>2]=f}},Fb=(a,b)=>{a.Mc||(a.Mc=a.getContext,a.getContext=function(d,e){e=a.Mc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.md?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Eb(c,b):0},Eb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.md,dd:a};a.canvas&&(a.canvas.Bd=d);zb[c]=d;("undefined"==typeof b.jd||b.jd)&&Gb(d);return c},Gb=a=>{a||=V;if(!a.Ad){a.Ad=!0;var b=a.dd;b.Sd=b.getExtension("WEBGL_multi_draw");b.Ld=b.getExtension("EXT_polygon_offset_clamp");b.Kd=b.getExtension("EXT_clip_control");b.ce=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.Id=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Pd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.hd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.hd)b.hd=b.getExtension("EXT_disjoint_timer_query");tb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Hb=(a,b,c,d,e,h)=>{a={target:J(a),Dc:h,Gc:d,Hc:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},Fc:c};I(a)},Ib=(a,b,c,d)=>{H.ad||(H.ad=M(96));return I({target:a,Sc:!0,Dc:"wheel",Gc:d,Hc:(e=event)=>{var h=H.ad;kb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
u[h+88>>2]=e.deltaMode;K(d)(9,h,b)&&e.preventDefault()},Fc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=[null,[],[]],Ob=[],Pb=()=>{var a=tb(N);
return a=a.concat(a.map(b=>"GL_"+b))},Qb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Pb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},Rb=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Sb=a=>{var b=Rb(a)+1,c=M(b);c&&L(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},Vb=(a,b,c,d,e)=>{a=Ub(a);b=d*((Cb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Bb-1&-Bb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=N.yd;if(b){var c=b.Nc[a];"number"==typeof c&&(b.Nc[a]=c=N.getUniformLocation(b,b.vd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Wb=[],Yb=a=>{var b=Rb(a)+1,c=Xb(b);L(a,c,b);return c},ac=a=>{var b=Zb();a();$b(b)};g.requestAnimationFrame=Oa;g.pauseMainLoop=$a;g.resumeMainLoop=function(){Ra++;var a=Ka,b=La,c=D;D=null;Za(c,0,!1,Sa,!0);Qa(a,b);E()};g.preMainLoop&&Xa.push(g.preMainLoop);g.postMainLoop&&Ya.push(g.postMainLoop);for(var Y=0;32>Y;++Y)Ob.push(Array(Y));
var bc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=bc.subarray(0,Y);var cc=new Int32Array(288);for(Y=0;288>=Y;++Y)Wb[Y]=cc.subarray(0,Y);
var pc={ka:function(){return 0},pb:function(){return 0},qb:function(){},tb:()=>sa(""),ib:()=>{Ca=!1;Ea=0},jb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ja(()=>dc(a,performance.now()))},b);C[a]={id:c,ae:b};return 0},eb:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Sb(a):0},ec:function(a,b){void 0!==window.localStorage&&(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},
Va:()=>{$a();D=null},da:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,fa:(a,b,c)=>{a=J(a);if(!a)return-4;a=fb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},w:()=>performance.now(),Wa:()=>performance.now(),$a:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},kb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+
65535)/65536|0;try{na.grow(d);ra();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},N:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),ca:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),X:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),V:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),W:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),bb:(a,b,c)=>{a=K(a);Za(a,b,c)},ba:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),_:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),Z:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),$:(a,b,
c,d)=>lb(a,b,c,d,8,"mousemove"),aa:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),Q:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Mc||document.body.cd||document.body.bd))return-1;a=J(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,"mspointerlockchange");return mb(a,b,c,d,"pointerlockchange")},P:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Mc||document.body.cd||document.body.bd))return-1;
a=J(a);if(!a)return-4;nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return nb(a,b,c,d,"pointerlockerror")},ea:(a,b,c,d)=>ob(a,b,c,d),R:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),S:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),T:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),U:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),M:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},L:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},Y:(a,b,c,d)=>(a=J(a))?"undefined"!=
typeof a.onwheel?Ib(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],md:u[c+4],Rd:u[c+5],jd:r[b+24],zd:r[b+25],Ud:u[c+7],Yd:r[b+32]};a=J(a);return!a||b.zd?0:Fb(a,b)},Za:a=>{V=zb[a];g.ctx=N=V?.dd;return!a||N?0:-5},rb:(a,b)=>{var c=0;Mb().forEach((d,e)=>{var h=b+c;e=v[a+4*e>>2]=h;for(h=0;h<d.length;++h)r[e++]=d.charCodeAt(h);
r[e]=0;c+=d.length+1});return 0},sb:(a,b)=>{var c=Mb();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},ja:()=>52,ob:()=>52,lb:function(){return 70},mb:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=t[f+n],w=Nb[a];0===p||10===p?((1===a?la:m)(B(w)),w.length=0):w.push(p)}e+=l}v[d>>2]=e;return 0},p:a=>N.activeTexture(a),va:(a,b)=>{N.attachShader(O[a],R[b])},b:(a,b)=>{35051==a?N.gd=b:35052==a&&(N.Kc=b);N.bindBuffer(a,vb[b])},a:(a,
b,c)=>{N.bindBufferBase(a,b,vb[c])},l:(a,b)=>{N.bindFramebuffer(a,wb[b])},Ga:(a,b)=>{N.bindRenderbuffer(a,xb[b])},o:(a,b)=>{N.bindSampler(a,S[b])},d:(a,b)=>{N.bindTexture(a,P[b])},K:a=>{N.bindVertexArray(yb[a])},G:(a,b,c,d)=>N.blendColor(a,b,c,d),H:(a,b)=>N.blendEquationSeparate(a,b),I:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),xb:(a,b,c,d,e,h,f,l,n,p)=>N.blitFramebuffer(a,b,c,d,e,h,f,l,n,p),Ja:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+
b):b,d)},A:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},pa:a=>N.checkFramebufferStatus(a),Sb:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),na:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Rb:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},q:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Wb:a=>{N.compileShader(R[a])},Aa:(a,b,c,d,e,h,f,l)=>{2<=V.version?N.Kc||!f?N.compressedTexImage2D(a,b,c,d,e,h,f,l):N.compressedTexImage2D(a,b,c,d,e,h,t,l,f):N.compressedTexImage2D(a,b,c,d,e,h,t.subarray(l,
l+f))},ya:(a,b,c,d,e,h,f,l,n)=>{N.Kc?N.compressedTexImage3D(a,b,c,d,e,h,f,l,n):N.compressedTexImage3D(a,b,c,d,e,h,f,t,n,l)},ac:()=>{var a=Db(O),b=N.createProgram();b.name=a;b.Qc=b.Oc=b.Pc=0;b.$c=1;O[a]=b;return a},Yb:a=>{var b=Db(R);R[b]=N.createShader(a);return b},D:a=>N.cullFace(a),Na:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=vb[d];e&&(N.deleteBuffer(e),e.name=0,vb[d]=null,d==N.gd&&(N.gd=0),d==N.Kc&&(N.Kc=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=wb[d];e&&(N.deleteFramebuffer(e),
e.name=0,wb[d]=null)}},m:a=>{if(a){var b=O[a];b?(N.deleteProgram(b),b.name=0,O[a]=null):T||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=xb[d];e&&(N.deleteRenderbuffer(e),e.name=0,xb[d]=null)}},g:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},z:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},C:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=P[d];e&&(N.deleteTexture(e),e.name=0,P[d]=null)}},La:(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2];N.deleteVertexArray(yb[d]);yb[d]=null}},u:a=>N.depthFunc(a),t:a=>{N.depthMask(!!a)},e:a=>N.disable(a),J:a=>{N.disableVertexAttribArray(a)},zb:(a,b,c)=>{N.drawArrays(a,b,c)},Ab:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},oa:(a,b)=>{for(var c=Ob[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];N.drawBuffers(c)},Bb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Cb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},j:a=>N.enable(a),Nb:a=>{N.enableVertexAttribArray(a)},qa:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,xb[d])},
n:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,P[d],e)},x:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,P[c],d,e)},E:a=>N.frontFace(a),Ka:(a,b)=>{U(a,b,"createBuffer",vb)},ra:(a,b)=>{U(a,b,"createFramebuffer",wb)},Ha:(a,b)=>{U(a,b,"createRenderbuffer",xb)},bc:(a,b)=>{U(a,b,"createSampler",S)},Ea:(a,b)=>{U(a,b,"createTexture",P)},Ua:(a,b)=>{U(a,b,"createVertexArray",yb)},Ub:(a,b)=>N.getAttribLocation(O[a],b?B(t,b):""),c:(a,b)=>Qb(a,b),_b:(a,b,c,d)=>{a=N.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");
b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},ua:(a,b,c)=>{if(c)if(a>=ub)T||=1281;else if(a=O[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Qc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Qc=Math.max(a.Qc,N.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Qc}else if(35722==b){if(!a.Oc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Oc=Math.max(a.Oc,N.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Oc}else if(35381==b){if(!a.Pc)for(d=
N.getProgramParameter(a,35382),b=0;b<d;++b)a.Pc=Math.max(a.Pc,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Pc}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},Vb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(u[c>>2]=b)},sa:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=N.getShaderParameter(R[a],b):T||=1281},Sa:(a,
b)=>{if(2>V.version)return T||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Pb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ta:(a,b)=>{b=b?B(t,b):"";if(a=O[a]){var c=a,d=c.Nc,e=c.wd,h;if(!d){c.Nc=d={};c.vd={};var f=N.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=N.getActiveUniform(c,h);var n=l.name;l=l.size;var p=Tb(n);p=0<p?n.slice(0,p):n;var w=c.$c;c.$c+=l;e[p]=[l,w];for(n=0;n<l;++n)d[w]=n,c.vd[w++]=p}}c=
a.Nc;d=0;e=b;h=Tb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.wd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},wb:(a,b,c)=>{for(var d=Ob[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];N.invalidateFramebuffer(a,d)},$b:a=>{a=O[a];N.linkProgram(a);a.Nc=0;a.wd={}},Ta:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);N.pixelStorei(a,b)},F:(a,b)=>N.polygonOffset(a,b),yb:a=>N.readBuffer(a),Fa:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),wa:(a,b,c)=>{N.samplerParameterf(S[a],
b,c)},h:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},r:(a,b,c,d)=>N.scissor(a,b,c,d),Xb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=v[c+4*h>>2])?B(t,f,d?v[d+4*h>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Qa:(a,b,c)=>N.stencilFunc(a,b,c),ma:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),s:a=>N.stencilMask(a),Pa:(a,b,c)=>N.stencilOp(a,b,c),la:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),za:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(N.Kc){N.texImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var p=Ub(l);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);
N.texImage2D(a,b,c,d,e,h,f,l,p,n);return}}p=n?Vb(l,f,d,e,n):null;N.texImage2D(a,b,c,d,e,h,f,l,p)},cc:(a,b,c,d,e,h,f,l,n,p)=>{if(N.Kc)N.texImage3D(a,b,c,d,e,h,f,l,n,p);else if(p){var w=Ub(n);N.texImage3D(a,b,c,d,e,h,f,l,n,w,p>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else N.texImage3D(a,b,c,d,e,h,f,l,n,null)},Da:(a,b,c)=>N.texParameteri(a,b,c),Ca:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,h)=>N.texStorage3D(a,b,c,d,e,h),vb:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(N.Kc){N.texSubImage2D(a,b,c,
d,e,h,f,l,n);return}if(n){var p=Ub(l);N.texSubImage2D(a,b,c,d,e,h,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}n=n?Vb(l,f,e,h,n):null;N.texSubImage2D(a,b,c,d,e,h,f,l,n)},ub:(a,b,c,d,e,h,f,l,n,p,w)=>{if(N.Kc)N.texSubImage3D(a,b,c,d,e,h,f,l,n,p,w);else if(w){var Q=Ub(p);N.texSubImage3D(a,b,c,d,e,h,f,l,n,p,Q,w>>>31-Math.clz32(Q.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,f,l,n,p,null)},Mb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=
x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Zb:(a,b)=>{N.uniform1i(W(a),b)},Ib:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Wb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Lb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Gb:(a,b,c)=>{if(2<=
V.version)b&&N.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Wb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Kb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;
for(var d=Wb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Wb[b],e=0;e<b;e+=
4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Db:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+
14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},i:a=>{a=O[a];N.useProgram(a);N.yd=a},Ob:(a,b)=>{N.vertexAttribDivisor(a,b)},Pb:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},k:(a,b,c,d)=>N.viewport(a,b,c,d),hb:Ga,ab:function(){g.pd=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.pd)},Xa:function(){g.ud=a=>{const b=a.clipboardData.getData("text");ac(()=>{const c=Yb(b);fc(c)})};window.addEventListener("paste",
g.ud)},Ma:function(){g.Zd=[];g.qd=b=>{b.stopPropagation();b.preventDefault()};g.rd=b=>{b.stopPropagation();b.preventDefault()};g.sd=b=>{b.stopPropagation();b.preventDefault()};g.td=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.$d=c;gc(c.length);for(let e=0;e<c.length;e++)ac(()=>{const h=Yb(c[e].name);hc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};const a=g.Ic;a.addEventListener("dragenter",g.qd,!1);a.addEventListener("dragleave",
g.rd,!1);a.addEventListener("dragover",g.sd,!1);a.addEventListener("drop",g.td,!1)},Qb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},dc:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?eb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.Ic=J(a);g.Ic||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.Ic.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Ya:function(){window.removeEventListener("beforeunload",g.pd)},Ra:function(){window.removeEventListener("paste",g.ud)},Ia:function(){const a=g.Ic;a.removeEventListener("dragenter",g.qd);a.removeEventListener("dragleave",g.rd);a.removeEventListener("dragover",g.sd);a.removeEventListener("drop",g.td)},y:function(){g.Ic&&g.Ic.requestPointerLock&&g.Ic.requestPointerLock()},Tb:function(a,b){if(g.Ic){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;
case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Ic.style.cursor=a}},Hb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";
a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Oa:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},cb:function(){const a=
(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];ac(()=>{const e=Yb(c),h=Yb(d);jc(e,h)})}},fb:function(){return g.Jc?g.Jc.bufferSize:0},nb:function(a,b,c){g.Cc=null;g.Jc=null;"undefined"!==typeof AudioContext?g.Cc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.Cc=null,console.log("sokol_audio.h: no WebAudio support"));return g.Cc?(console.log("sokol_audio.h: sample rate ",g.Cc.sampleRate),g.Jc=g.Cc.createScriptProcessor(c,
0,b),g.Jc.onaudioprocess=d=>{const e=d.outputBuffer.length,h=kc(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=x[(h>>2)+(f*p+l)]}}},g.Jc.connect(g.Cc.destination),a=()=>{g.Cc&&"suspended"===g.Cc.state&&g.Cc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},gb:function(){return g.Cc?g.Cc.sampleRate:0},
ia:function(){const a=g.Cc;null!==a&&(g.Jc&&g.Jc.disconnect(),a.close(),g.Cc=null,g.Jc=null)},db:function(){if(g.Cc)return"suspended"===g.Cc.state?1:0},v:function(a,b,c,d,e,h){b=b?B(t,b):"";const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const l=0<d;l&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!l){const n=new Uint8Array(f.response),p=n.length;p<=h?(t.set(n,e),lc(a,
d,p)):mc(a)}else nc(a,f.status)};f.send()},ha:function(a,b){b=b?B(t,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");oc(a,d)}else nc(a,c.status)};c.send()},xa:function(){return navigator.userAgent.includes("Macintosh")?1:0},ga:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},
Z;(async function(){function a(c){Z=c.exports;na=Z.fc;ra();hb=Z.xc;z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;g.monitorRunDependencies?.(z);var b={a:pc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ta??=g.locateFile?g.locateFile("numbersid.wasm",k):k+"numbersid.wasm";return a((await wa(b)).instance)})();var M=a=>(M=Z.hc)(a);g._fs_emsc_alloc=a=>(g._fs_emsc_alloc=Z.ic)(a);
g._fs_emsc_load_snapshot_callback=(a,b,c)=>(g._fs_emsc_load_snapshot_callback=Z.jc)(a,b,c);var fc=g.__sapp_emsc_onpaste=a=>(fc=g.__sapp_emsc_onpaste=Z.kc)(a),ec=g.__sapp_html5_get_ask_leave_site=()=>(ec=g.__sapp_html5_get_ask_leave_site=Z.lc)(),gc=g.__sapp_emsc_begin_drop=a=>(gc=g.__sapp_emsc_begin_drop=Z.mc)(a),hc=g.__sapp_emsc_drop=(a,b)=>(hc=g.__sapp_emsc_drop=Z.nc)(a,b),ic=g.__sapp_emsc_end_drop=(a,b,c)=>(ic=g.__sapp_emsc_end_drop=Z.oc)(a,b,c);
g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.pc)(a,b,c,d,e,h,f,l);
var qc=g._main=(a,b)=>(qc=g._main=Z.qc)(a,b),kc=g.__saudio_emsc_pull=a=>(kc=g.__saudio_emsc_pull=Z.rc)(a),jc=g.__sargs_add_kvp=(a,b)=>(jc=g.__sargs_add_kvp=Z.sc)(a,b),oc=g.__sfetch_emsc_head_response=(a,b)=>(oc=g.__sfetch_emsc_head_response=Z.tc)(a,b),lc=g.__sfetch_emsc_get_response=(a,b,c)=>(lc=g.__sfetch_emsc_get_response=Z.uc)(a,b,c),nc=g.__sfetch_emsc_failed_http_status=(a,b)=>(nc=g.__sfetch_emsc_failed_http_status=Z.vc)(a,b),mc=g.__sfetch_emsc_failed_buffer_too_small=a=>(mc=g.__sfetch_emsc_failed_buffer_too_small=
Z.wc)(a),dc=(a,b)=>(dc=Z.yc)(a,b),$b=a=>($b=Z.zc)(a),Xb=a=>(Xb=Z.Ac)(a),Zb=()=>(Zb=Z.Bc)();function rc(a=[]){var b=qc;a.unshift(fa);var c=a.length,d=Xb(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Yb(f);e+=4});v[e>>2]=0;try{var h=b(c,d);Ha(h)}catch(f){Fa(f)}}
function sc(a=ea){function b(){g.calledRun=!0;if(!q){Z.gc();g.onRuntimeInitialized?.();g.noInitialRun||rc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();za.unshift(c)}ya(za)}}if(0<z)A=sc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ba();ya(Aa);0<z?A=sc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();sc();
