#import "sinebob_macros.asm"

// --- params

// paramters: for each sine, a frequency, scaled by 256. Added to counter each frame.
// range 0-65536; 256 means one cycle every 256 frames
freqs:
.fillword MAX_SINES,0

// paramters: for each sine, an amplitude
// Note: we store word values to make indexing simpler (all others are words)
// But we only use low byte, value <=256
amplitudes:
.fillword MAX_SINES,0

// parameter: for each bob, the phase; added to counter before lookup in sine table
// Note: we store word values to make indexing simpler (all others are words)
// But we only use low byte, value <=256
phases:
.fillword MAX_SINES,0

bob_colors:
.fillword MAX_BOBS,0

bob_steps:
.fillword MAX_BOBS,0

bob_enables:
.fillword MAX_BOBS,0

bob_position_xs:
.fillword MAX_BOBS,0

bob_position_ys:
.fillword MAX_BOBS,0

// note: will be generated by code
//bob_num_orbits:
//.byte NUM_BOBS,1

// ------------ computed--------

// for each bob; a full sine cycle is 65536 counts
counters:
.fillword MAX_SINES,0

// for each sine, the position/value of sine.
sine_values:
.fillword MAX_SINES, 0

// positions of bobs (note: byte values, not like parameters!)
bob_xs: 
.byte MAX_BOBS,0
bob_ys: 
.byte MAX_BOBS,0

// offset in the charset where transitions are to be updated
// note: offset in bytes, so 8 bytes per char, increase insteps of 8 
sinebob_transition_offset:
.word 0

// current character animation step used for each sinebob
// (add #BOB_CHAR_START) to get character 
// range 0-128 
sinebob_step_counters:
.fill MAX_BOBS, 0

// a history of screen adresses to clear
clear_pixel_history:
.fillword CLEAR_HISTORY_SIZE_MAX, 0

// 32 sine tables, scale 1-32 
sine_tables:
.fill 32*256, 0
